const QUERRY_START = "QUERRY_START";
const QUERRY_SUCCESS = "QUERRY_SUCCESS";
const QUERRY_FAIL = "QUERRY_FAIL";
const ADD_INTENT = "ADD_INTENT";
const VISIBILITY = "VISIBILITY";
export { QUERRY_START, QUERRY_SUCCESS, QUERRY_FAIL, ADD_INTENT, VISIBILITY };
